### ISSUE TITLE
Android O DowloadService crash

### ISSUE THREAD

**Issue by yu2z** [bolein/better-apk-expansion#12]
Please, consider this crash on API level 26 and up

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.myapp/com.google.android.vending.expansion.downloader.impl.DownloaderService (has extras) }: app is in background uid UidRecord{d630e58 u0a140 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.google.android.vending.expansion.downloader.impl.DownloaderService.startDownloadServiceIfRequired(DownloaderService.java:675)
       at com.google.android.vending.expansion.downloader.impl.DownloaderService$AlarmReceiver.onReceive(DownloaderService.java:990)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3266)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6637)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.grinasys.weightlossgoogleplay/com.google.android.vending.expansion.downloader.impl.DownloaderService (has extras) }: app is in background uid UidRecord{d630e58 u0a140 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.google.android.vending.expansion.downloader.impl.DownloaderService.startDownloadServiceIfRequired(DownloaderService.java:675)
       at com.google.android.vending.expansion.downloader.impl.DownloaderService$AlarmReceiver.onReceive(DownloaderService.java:990)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3266)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6637)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by ReckeDJ** [comment]
Same here!

**Comment by johngoren** [comment]
Ever figure this out? I'd love to work with people to make APK Expansion downloading a more humane process.

**Comment by afgaiel** [comment]
Did you find a solution for this problem?

**Comment by Guy-kun** [comment]
This library is outdated and cannot used on Android O.
startService() is no longer allowed to be called and startForegroundService() must be used instead (followed by startForeground())
Anyone facing the issue should update the code themselves or find an alternative.

**Comment by vadymhimself** [comment]
@Guy-kun we would all appreciate your pull request!

**Comment by Guy-kun** [comment]
Myself, and likely many developers using .obb are currently praying that the increased .aab size of 1GB will become public soon (Google has teased this in an early preview via email: and not given us access...) so I think it's not worth putting extensive development into obb support at this time, sorry.

It is very much a 'keep it from breaking until we can finally cut it out and remove it fully'

**Comment by johngoren** [comment]
Oh wow that's fascinating. I wonder how soon the change will happen. Would be great to just switch to huge .aabs.

**Comment by Guy-kun** [comment]
Yep, see below (the link has long become a 404)
<img width="544" alt="Screen Shot 2019-10-04 at 14 59 22" src="https://user-images.githubusercontent.com/1477129/66213403-971a5600-e6b7-11e9-8a74-9262a0abc1c5.png">

**Comment by johngoren** [comment]
You know what, I might just switch to a plain old HTTP file download from Digital Ocean until this change blows over...I've been wondering how developers are coping with such a bizarre system.

**Comment by Oldes** [comment]
@johngoren yes.. we can host OBB files on our servers, but for what than Google takes 30% from the price? It's really very bad from them, that **they require us to target API 28, but they don't care providing any line of code to help us**... just deprecate more and more APIs. **The original Google's sample of this project is still at target 23!**

**Comment by johngoren** [comment]
Wonder if there have been any further rumors about increased .aab size of 1 GB. Was this something that was talked about at the recent Android developer summit?

**Comment by Guy-kun** [comment]
Google have since off-hand announced 'Asset Packs', yet again in 'closed testing' with the promise of being the replacement to obb for .aab.
Still no public information though... These things seem to take full years to come around

**Comment by johngoren** [comment]
Video warriors, the day has come at last. Has anyone had any luck testing and setting up install-time Dynamic Asset Delivery as a replacement for expansion packs? It feels a bit underdocumented and I'm trying to understand whether I need to use something called FakeSplitInstallManager to replace my old testing OBB. UPDATE: You don't need a FakeSplitInstallManager.

**Comment by Guy-kun** [comment]
Asset Packs have been finally released and seem to be promising? We've experimented with them and they 'just work' across all android version (using install-time delivery).
Everything is looking top-shape and this gives you a perfect opportunity to delete hundreds of lines of code which is a pleasure.

Haven't shipped it in production yet but fingers are crossed!

**Comment by johngoren** [comment]
That is wonderful news. 

Edit: I just figured out how to build a debug build with it and it's great.
