### ISSUE TITLE
DownloaderService get NPE

### ISSUE THREAD

**Issue by ricky7777** [bolein/better-apk-expansion#14]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.content.Intent.getParcelableExtra(java.lang.String)' on a null object reference
       at com.google.android.vending.expansion.downloader.impl.DownloaderService.onHandleIntent(DownloaderService.java:1017)
       at com.google.android.vending.expansion.downloader.impl.CustomIntentService$ServiceHandler.handleMessage(CustomIntentService.java:100)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)`

intent.getParcelableExtra(EXTRA_PENDING_INTENT)
or when intent == null || intent.getParcelableExtra(EXTRA_PENDING_INTENT) == null
return?

**Comment by ricky7777** [comment]
already solved
